<?php
$paginator = $this->paginator;
if ($paginator->count()) { 
?>



<?php } // end - if ($paginator->count) { ?>
 <?php foreach($this->modules as $module) { ?>
        <div class="row-fluid module-row">
            <div class="span12">
                <div class="row-fluid">
                    <div class="module-info">
                        <div class="span6 module-author">
                            <div class="row-fluid">
                                <div class="span2">
                                    <img src="<?php echo $module['photoUrl']?>" alt="<?php echo $module['owner']?>">
                                </div>
                                <div class="span10">
                                    <strong><?php echo $module['owner']?></strong>
                                    <p>
                                        <span class="author-label">Github:</span>
                                        <a href="<?php echo $module['url']?>"><?php echo $module['name']?></a>
                                        <!--
                                  <span class="author-label">Blog:</span> <a>placeholder</a><br />
                                  <span class="author-label">Modules:</span> <a>5</a><br /><br />
                                  <span class="author-label"><a>More info...</a>-->
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="span6">
                            <strong><a href="<?php
                                            echo
                                            $this->url('view-module', array(
                                                    'vendor' => $module['owner'],
                                                    'module' =>  $module['name'],
                                                )
                                            );?>"><?php echo $module['name'] ?></a></strong>
                            <p>
                                <!--<span class="author-label">Version:</span> 1.2.1<br />-->
                                 <span class="author-label">Created:</span> <?php
                                                            $date =  $module['createdAt']; 
                                                            echo $date->format('Y-m-d');
                                                            ?><br>
                                <!--<span class="author-label">Edited:</span> <a>15 days ago</a><br />
                            <span class="author-label">Tags:</span>
                            <span class="label">zf2</span>
                            <span class="label">Assetic</span>
                            <span class="label">Assets</span>
                            <span class="label">Sx</span>-->
                            </p>
                        </div>
                        <div style="clear: both;"></div>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="module-description">
                        <div class="span12">
                            <p>
                                <?php echo $module['description']?>
                            </p>
                        </div>
                        <div style="clear: both;"></div>
                    </div>
                </div>
            </div>
            
        </div>
           
        <?php echo $this->paginationControl($this->repositories, 'Sliding', 'application/index/pagination', array('query' =>$query)); ?>
    
            <?php } ?>