<?php /** @todo rm this - is mvd to ../comments  */ ?>
<div class="module-child-comment-wrapper">
    <div>
        <span class="module-comments-username">
            <span class="comment-discriptor-label"><?= $this->translate('Username') ?> : </span>
            <strong><?= $this->EscapeHtml($comment->getUser()->getUserName()) ?> </strong>
        </span>
    </div>
    <div>
        <span class="module-comments-comment"><?= $this->EscapeHtml($comment->getComment()) ?> </span>
    </div> 
</div><!-- end class="module-comment-wrapper" -->