<?php  /** @todo refactor location & tidy ?> */ 
  $comments = $this->comments;
  $moduleId = $this->moduleId;   ?>

<div id="module-comments-wrapper" module-id="<?=  $moduleId ?>"  class="block">
    
    <div class="row">
      
        <span class="module-comments-title span4"><h4><?= $this->translate('Comments') ?></h4></span>
       
    </div><!-- end // class="row" -->
    <div class="module-comment-container">
    <?php
    if (count($comments)) {
        //loop to display comments
        foreach ($comments as $key => $comment) {
            echo $this->partial('zf-module/comment/comment.phtml',
                                array('comment' => $comment , 'moduleId' => $moduleId));
            ?>

           

        <?php } // - foreach ($comments as $key => $comment) { ?>

    <?php } else { // end - if (count($comments)){  ?> 
        <span class="module-comments-no-comments"><?= $this->translate('Be the first') ?></span>

    <?php } // end else   ?>
        </div> <!-- end -  class="module-comment-container"-->
    <?php if ($this->zfcUserIdentity() || 1) { //debugcode ?>
        <div class="add-new-comment-wrapper">
        <span class="new-comment-button comment-button"><strong><?= $this->translate('Add New Comment') ?></strong></span>
      <?=  $this->renderChildModel('commentForm') ?>
       
        </div><!-- end -class="add-new-comment-wrapper" -->
    <?php } else { ?>
        <a><?= $this->translate('Login to add new comment') ?></a>
    <?php } // end else ?>
</div><!-- end - id="module-comments-wrapper" -->
